### ISSUE TITLE
beets needs a patch

### ISSUE THREAD

**Issue by thedaemon** [ghostbsd/ghostbsd-ports#46]
Currently when running beets, (beet) it has an error like so. I was informed by an OpenBSD dev that this is the correct patch to fix it. [Patch from OpenBSD](https://github.com/openbsd/ports/blob/master/audio/beets/patches/patch-beets_util_functemplate_py)

here is the error when running beets.
`❯ beet
Traceback (most recent call last):
  File "/usr/local/bin/beet", line 33, in <module>
    sys.exit(load_entry_point('beets==1.4.9', 'console_scripts', 'beet')())
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1249, in _raw_main
    subcommands, plugins, lib = _setup(options, lib)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1144, in _setup
    lib = _open_library(config)
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 1201, in _open_library
    get_path_formats(),
  File "/usr/local/lib/python3.8/site-packages/beets/ui/__init__.py", line 619, in get_path_formats
    path_formats.append((query, template(view.as_str())))
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 571, in template
    return Template(fmt)
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 581, in __init__
    self.compiled = self.translate()
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 614, in translate
    func = compile_func(
  File "/usr/local/lib/python3.8/site-packages/beets/util/functemplate.py", line 155, in compile_func
    prog = compile(mod, '<generated>', 'exec')
ValueError: Name node can't be used with 'None' constant
`

I am testing the patch soon.

**Comment by thedaemon** [comment]
I tested this patch on my system. beet works after. verified as a working patch.

**Comment by ericbsd** [comment]
This needs to be reported to FreeBSD bug or the port maintainer.
